<?php /* testLongOpenTagWithNewLine */ ?>
<?php
echo 'with new line';
?>

<?php /* testLongOpenTagWithOneSpaceAndNewLine */ ?>
<?php 
echo 'with one space and new line';
?>

<?php /* testLongOpenTagWithTrailingWhiteSpaceAndNewLine */ ?>
<?php    
echo 'with trailing whitespace and new line';
?>

<?php /* testLongOpenTagOneSpace */ ?>
<?php echo 'single line, one space'; ?>

<?php /* testLongOpenTagMultiSpace */ ?>
<?php      echo 'single line, multiple spaces'; ?>

<?php /* testLongOpenTagWithDoubleNewLine */ ?>
<?php

echo 'with double new line';
?>

<?php /* testLongOpenTagWithTripleNewLine */ ?>
<?php


echo 'with triple new line';
?>

<?php /* testLongOpenTagWithNewLineAndIndentOnNextLine */ ?>
    <?php
    echo 'with new line and indent on next line';
?>

<!-- ====================================== -->

<?php /* testCaseLongOpenTagWithNewLine */ ?>
<?PHP
echo 'with new line';
?>

<?php /* testCaseLongOpenTagWithOneSpaceAndNewLine */ ?>
<?phP 
echo 'with one space and new line';
?>

<?php /* testCaseLongOpenTagWithTrailingWhiteSpaceAndNewLine */ ?>
<?Php    
echo 'with trailing whitespace and new line';
?>

<?php /* testCaseLongOpenTagOneSpace */ ?>
<?pHp echo 'single line, one space'; ?>

<?php /* testCaseLongOpenTagMultiSpace */ ?>
<?phP      echo 'single line, multiple spaces'; ?>

<!-- ====================================== -->

<?php /* testShortOpenEchoTagWithNewLine */ ?>
<?=
'with new line';
?>

<?php /* testShortOpenEchoTagWithOneSpaceAndNewLine */ ?>
<?= 
'with one space and new line';
?>

<?php /* testShortOpenEchoTagWithTrailingWhiteSpaceAndNewLine */ ?>
<?=    
'with trailing whitespace and new line';
?>

<?php /* testShortOpenEchoTagNoSpace */ ?>
<?='single line, no space'; ?>

<?php /* testShortOpenEchoTagOneSpace */ ?>
<?= 'single line, one space'; ?>

<?php /* testShortOpenEchoTagMultiSpace */ ?>
<?=      'single line, multiple spaces'; ?>

<!-- ====================================== -->

<?php /* testShortOpenTagWithNewLine */ ?>
<?
echo 'with new line';
?>

<?php /* testShortOpenTagWithOneSpaceAndNewLine */ ?>
<? 
echo 'with one space and new line';
?>

<?php /* testShortOpenTagWithTrailingWhiteSpaceAndNewLine */ ?>
<?    
echo 'with trailing whitespace and new line';
?>

<?php /* testShortOpenTagNoSpace */ ?>
<?echo 'single line, no space'; ?>

<?php /* testShortOpenTagOneSpace */ ?>
<? echo 'single line, one space'; ?>

<?php /* testShortOpenTagMultiSpace */ ?>
<?      echo 'single line, multiple spaces'; ?>

<!-- ====================================== -->
