<?php

// phpcs:set Squiz.Commenting.VariableComment useShortTypes false

class UsingLongTypes
{
    /**
     * @var bool
     */
    public $typeBool;

    /**
     * @var boolean
     */
    public $typeBoolean;

     /**
      * @var int
      */
     public $typeInt;

     /**
      * @var integer
      */
     public $typeInteger;
}

// phpcs:set Squiz.Commenting.VariableComment useShortTypes true

class UsingShortTypes
{
    /**
     * @var bool
     */
    public $typeBool;

    /**
     * @var boolean
     */
    public $typeBoolean;

     /**
      * @var int
      */
     public $typeInt;

     /**
      * @var integer
      */
     public $typeInteger;
}
