<?php

for ($same = 0; $same < 20; $same++) {
    for ($j = 0; $j < 5; $same += 2) {
        for ($k = 0; $k > 3; $same++) {
            
        }
    }
}

for ($i = 0; $i < 20; $i++) {
    for ($j = 0; $j < 5; $j += 2) {
        for ($k = 0; $k > 3; $k++) {
            
        }
    }
}

for ($i = 0; $i < 20; $i++) {
    for ($same = 0; $same < 5; $same += 2) {
        for ($k = 0; $k > 3; $same++) {
            
        }
    }
}