<?php
declare(ticks=1);
declare (ticks=1);
declare( ticks=1);
declare(ticks =1);
declare(ticks= 1);
declare(ticks=1 );
declare(ticks=1) ;
declare	(ticks=1);
declare(	ticks=1);
declare(ticks	=1);
declare(ticks=	1);
declare(ticks=1	);
declare(ticks=1)	;
declare 	 (ticks=1);
declare( 	 ticks=1);
declare(ticks 	 =1);
declare(ticks= 	 1);
declare(ticks=1 	 );
declare(ticks=1) 	 ;
declare
(ticks=1);
declare(
ticks=1);
declare(ticks
=1);
declare(ticks=
1);
declare(ticks=1
);
declare(ticks=1)
;
declare 
 (ticks=1);
declare( 
 ticks=1);
declare(ticks 
 =1);
declare(ticks= 
 1);
declare(ticks=1 
 );
declare(ticks=1) 
 ;
declare/* test */(ticks=1);
declare(/* test */ticks=1);
declare(ticks/* test */=1);
declare(ticks=/* test */1);
declare(ticks=1/* test */);
declare(ticks=1)/* test */;
declare(ticks=1);/* test */
declare// test
(ticks=1);
declare(// test
ticks=1);
declare(ticks// test
=1);
declare(ticks=// test
1);
declare(ticks=1// test
);
declare(ticks=1)// test
;
declare(ticks=1);// test
