<?php
/**
 * A collection of valid PHP for testing
 *
 * This file should have no errors when checked with either PHPStan or Psalm.
 * And no errors when checked with the PHPDoc types sniff, regardless of setting.
 *
 * @author    James Calder <jeg+accounts.github@cloudy.kiwi.nz>
 * @copyright 2024 Otago Polytechnic
 * @license   https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/licence.txt BSD Licence
 *            CC BY-SA 4.0 or later
 */

namespace MoodleHQ\MoodleCS\moodle\Tests\Sniffs\Commenting\fixtures {

    /**
     * A collection of valid PHP for testing
     */
    class PhpValid
    {


        /**
         * Namespaces recognised
         *
         * @param \MoodleHQ\MoodleCS\moodle\Tests\Sniffs\Commenting\fixtures\PhpValid $x
         *
         * @return void
         */
        public function namespaces(PhpValid $x): void
        {

        }//end namespaces()


    }//end class

}
