name: Deploy gh-pages branch to GitHub Pages

on:
  push:
    branches:
      - "gh-pages"
  # Do a dry-run (update, no deploy) for PRs.
  pull_request:
  # Allow running this workflow manually from the Actions tab.
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Permissions should be configured at the job level.
permissions: {}

jobs:
  build:
    permissions:
      contents: read # To clone the repo.

    # Don't run on forks.
    if: github.event.repository.fork == false

    name: "Build the website"
    runs-on: ubuntu-latest

    steps:
      # By default use the `gh-pages` branch.
      # For testing changes to the workflow or the scripts, use the PR branch
      # to have access to the latest version of the workflow/scripts.
      - name: Determine branch to use
        id: base_branch
        env:
          REF: ${{ github.ref }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=$REF" >> "$GITHUB_OUTPUT"
          else
            echo 'BRANCH=gh-pages' >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ steps.base_branch.outputs.BRANCH }}
          persist-credentials: false
      
      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
          ini-values: error_reporting=-1, display_errors=On, display_startup_errors=On, log_errors_max_len=0
          coverage: none

      - name: Generate /phars/index.html
        run: php build/generate_phars_list.php

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@f0ef9e1cf727f9f76f8485f8c525fa03afc4ec02 # v5.0.0
        with:
          pages_threshold: major_outage

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './src'
          
  deploy:
    permissions:
      pages: write # To deploy to Pages.
      id-token: write # To verify the deployment originates from an appropriate source.

    needs: build
    # Don't run on forks.
    if: github.repository == 'PHPCSStandards/PHP_CodeSniffer' && github.event_name != 'pull_request' && needs.build.result == 'success'

    name: "Deploy the website"
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
